version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: evolution_sistema-guia-db
    environment:
      POSTGRES_USER: sistemaguiadm
      POSTGRES_PASSWORD: 973574BBA
      POSTGRES_DB: sistema-guia-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sistemaguiadm -d sistema-guia-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
